eu_capitals = {
    "Vienna": "Austria",
    "Brussels": "Belgium",
    "Sofia": "Bulgaria",
    "Zagreb": "Croatia",
    "Nicosia": "Cyprus",
    "Prague": "Czech Republic",
    "Copenhagen": "Denmark",
    "Tallinn": "Estonia",
    "Helsinki": "Finland",
    "Paris": "France",
    "Berlin": "Germany",
    "Athens": "Greece",
    "Budapest": "Hungary",
    "Dublin": "Ireland",
    "Rome": "Italy",
    "Riga": "Latvia",
    "Vilnius": "Lithuania",
    "Luxembourg": "Luxembourg",
    "Valletta": "Malta",
    "Amsterdam": "Netherlands",
    "Warsaw": "Poland",
    "Lisbon": "Portugal",
    "Bucharest": "Romania",
    "Bratislava": "Slovakia",
    "Ljubljana": "Slovenia",
    "Madrid": "Spain",
    "Stockholm": "Sweden"
}

eu_capital_currencies = {
    "Vienna": "Euro",
    "Brussels": "Euro",
    "Sofia": "Bulgarian Lev",
    "Zagreb": "Euro",
    "Nicosia": "Euro",
    "Prague": "Czech Koruna",
    "Copenhagen": "Danish Krone",
    "Tallinn": "Euro",
    "Helsinki": "Euro",
    "Paris": "Euro",
    "Berlin": "Euro",
    "Athens": "Euro",
    "Budapest": "Hungarian Forint",
    "Dublin": "Euro",
    "Rome": "Euro",
    "Riga": "Euro",
    "Vilnius": "Euro",
    "Luxembourg": "Euro",
    "Valletta": "Euro",
    "Amsterdam": "Euro",
    "Warsaw": "Polish Zloty",
    "Lisbon": "Euro",
    "Bucharest": "Romanian Leu",
    "Bratislava": "Euro",
    "Ljubljana": "Euro",
    "Madrid": "Euro",
    "Stockholm": "Swedish Krona"
}